language: ruby
rvm:
- 2.4.2

install: bundle install
script: bundle exec jekyll build

# branch whitelist, only for master branch
branches:
  only:
  - master     # test the master branch

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build
