language: ruby
rvm:
- 2.3.3

install: bundle install && gem install html-proofer
script: bundle exec jekyll build && htmlproofer --assume-extension --allow-hash-href --url-ignore "https://daltoncraven.tech" --file-ignore "/files/vb6.zip,./_site/files/vb6.zip" ./_site

# branch whitelist, only for master branch
branches:
  only:
  - master     # test the master branch

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build
