language: ruby

rvm:
- 2.3.3

install: bundle install && gem install html-proofer
script: bundle exec jekyll build && htmlproofer --assume-extension --allow-hash-href ./_site

branches:
  only:
  - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

sudo: false
