# jekyll-seo-tag
title: Mason ACM
url: "https://masonacm.org"
email: wmhsacm@gmail.com
description: >-
  Mason ACM is part of an international organization, ACM.
  ACM is an organization for computing professionals to deliver
  resources that advance computing as a science and a profession.
meetings: Mason ACM meets in Mr. Kummer's room (B109) on Tuesdays and Thursdays, starting at 2:20pm.
twitter:
  username: mason_acm
logo: /images/logo.png
social:
  links:
    - https://twitter.com/mason_acm
    - https://github.com/cravend/mason-acm-website

# data page generator

page_gen-dirs: true
page_gen:
- data: teams
  name: name
  title: teamname
  dir: teams

# general

plugins:
  - "jekyll-seo-tag"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
